import { NgModule } from '@angular/core';
import { MdAutocompleteModule,
         MdCheckboxModule,
         MdInputModule,
         MdRadioModule,
         MdSelectModule,
         MdSliderModule,
         MdSlideToggleModule,
         MdMenuModule,
         MdSidenavModule,
         MdToolbarModule,
         MdListModule,
         MdGridListModule,
         MdCardModule,
         MdTabsModule,
         MdButtonModule,
         MdButtonToggleModule,
         MdChipsModule,
         MdIconModule,
         MdProgressSpinnerModule,
         MdProgressBarModule,
         MdDialogModule,
         MdTooltipModule,
         MdSnackBarModule

        } from '@angular/material';

@NgModule({
  imports: [
        MdAutocompleteModule,
         MdCheckboxModule,
         MdInputModule,
         MdRadioModule,
         MdSelectModule,
         MdSliderModule,
         MdSlideToggleModule,
         MdMenuModule,
         MdSidenavModule,
         MdToolbarModule,
         MdListModule,
         MdGridListModule,
         MdCardModule,
         MdTabsModule,
         MdButtonModule,
         MdButtonToggleModule,
         MdChipsModule,
         MdIconModule,
         MdProgressSpinnerModule,
         MdProgressBarModule,
         MdDialogModule,
         MdTooltipModule,
         MdSnackBarModule

  ],
  exports: [
        MdAutocompleteModule,
         MdCheckboxModule,
         MdInputModule,
         MdRadioModule,
         MdSelectModule,
         MdSliderModule,
         MdSlideToggleModule,
         MdMenuModule,
         MdSidenavModule,
         MdToolbarModule,
         MdListModule,
         MdGridListModule,
         MdCardModule,
         MdTabsModule,
         MdButtonModule,
         MdButtonToggleModule,
         MdChipsModule,
         MdIconModule,
         MdProgressSpinnerModule,
         MdProgressBarModule,
         MdDialogModule,
         MdTooltipModule,
         MdSnackBarModule

  ],
})
export class MyMaterialModule { }
